name: Shellcheck
on:
  workflow_call:

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Shellcheck
      run: docker run --rm -v "$PWD:/mnt" koalaman/shellcheck:v0.8.0 ./**/*.sh



