name: Shellcheck
on:
  workflow_call:

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Shellcheck
      run: |
        .github/workflows/scripts/run-shellcheck.sh



