name: Terraform plan
on:
  workflow_call:
    inputs:
      role_name:
        required: true
        type: string
      module:
        required: true
        type: string
      aws_region:
        required: false
        type: string
        default: ca-central-1
      terraform_version:
        required: true
        type: string
      terragrunt_version:
        required: true
        type: string
      conftest_version:
        required: false
        type: string
        default: 0.35.0
      tf_summarize_version:
        required: false
        type: string
        default: 0.2.4

env:
  AWS_REGION: ca-central-1
  TERRAFORM_VERSION: ${{ inputs.terraform_version }}
  TERRAGRUNT_VERSION: ${{ inputs.terragrunt_version }}
  CONFTEST_VERSION: ${{ inputs.conftest_version}}
  TF_SUMMARIZE_VERSION: ${{ inputs.tf_summarize_version}}

permissions:
  id-token: write
  contents: read
  pull-requests: write
  actions: write
  checks: write
  statuses: write

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform Tools
        uses: cds-snc/terraform-tools-setup@v1

      - name: Configure aws credentials using OIDC
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::283582579564:role/${{ inputs.role_name }}
          aws-region: "ca-central-1"

      - name: Terraform Plan ${{ inputs.module }}
        uses: cds-snc/terraform-plan@v3
        with:
          comment-delete: true
          comment-title: Plan for ${{ inputs.module }}
          directory: ./${{ inputs.module }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          terragrunt: true