name: Test inherit

on:
  workflow_call:
  pull_request:
    paths:
      - "terraform/**"
      - ".github/workflows/**"

env:
  MY_SECRECT: ${{ secrets.FOO }}

jobs:
  test_inherit:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          echo "Hello this is a test $MY_SECRET"